[build]
  publish = "."
  command = "echo 'No build command required for static site'"

[build.environment]
  NODE_VERSION = "18"

[context.production]
  publish = "."

[context.deploy-preview]
  publish = "."

[context.branch-deploy]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.pdf"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/company"
  to = "/"
  status = 301 